# Generated by Django 2.0.2 on 2018-05-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='current_user',
            new_name='owner',
        ),
    ]
