# Generated by Django 2.0.2 on 2018-05-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
