# Generated by Django 2.0.2 on 2018-05-18 12:00

import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='plain_location',
            field=location_field.models.plain.PlainLocationField(default=django.contrib.gis.geos.point.Point(1, 1), max_length=63),
        ),
    ]
