# Generated by Django 2.0.2 on 2018-05-19 09:35

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20180518_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='plain_location',
        ),
        migrations.AddField(
            model_name='location',
            name='position',
            field=geoposition.fields.GeopositionField(default=1, max_length=42),
            preserve_default=False,
        ),
    ]
